spring:
  profiles:
      active: dev
logging:
    level:
        ROOT: INFO
        authentication: ERROR
        freemarker: OFF
        org.apache.catalina: ERROR
        org.springframework.boot: ERROR
        org.springframework.data: ERROR
        org.springframework.scheduling: ERROR
        org.springframework.web: ERROR
